### ISSUE TITLE
Not Working proberly

### ISSUE THREAD

**Issue by katzolik** [sandord/DpiGonzales#14]
I Have a 27" 16:9 4k 60Hz side by side with an 19" 5:4 1280x1024 60Hz.
And sadly the cursor speed is still much faster on the 19" with your new app running. 
With the old application i could dial it in perfectly.. sadly there was no save or auto start function!

**Comment by sandord** [comment]
I'll implement this soon: https://github.com/sandord/DpiGonzales/issues/5. That would help you tweak the relative mouse speeds between your displays.

By the way, you could add a new issue requesting the auto start function ;-)

**Comment by sandord** [comment]
I've just release v1.0.32. Can you try it, using the new settings window to set the speed ratio to 2 (just one notch above the default value of 1) and see if this makes your mouse pointer just about as fast on your 4K display as it is on your 1280x1024 display?

Please keep in mind that DpiGonzales does not slow down your mouse pointer. If you feel it is too fast on your low-DPI display, adjust mouse pointer settings in Windows to slow it down. Please exit DpiGonzales before doing so.

**Comment by katzolik** [comment]
The slider works but a more granular control would be needed as the speeds are still a bit different to each other.
Also setting the slider to 2 locks my windows mouse courser speed setting to a higher value. 
Even after closing DpiGonzales adjusting the cursor speed and starting it up again it will lock the windows cursor speed to the 8th position.

**Comment by sandord** [comment]
Sorry for the late reply. I know the speed control is rather course. Although the UI could provide a smoother setting, pointer speed in Windows is controlled in a similarly course precision. This means that one notch up on the speed ratio slider, equals one notch up on the pointer speed slider in the Windows control panel mouse settings. Since we don't want to create very large pointer speed differences, only a few notches make sense.

Perhaps I should replace the slider by a few radio buttons or a drop down menu.

Can you elaborate on the Windows cursor speed locking to the 8th position? I mean, how do you know it doesn't change? Keep in mind that it makes a difference on which display you're opening (not moving to) the mouse settings control panel if DpiGonzales is running.

Perhaps it would be nice to have an optional window that displays the current mouse speed.
