### ISSUE TITLE
Doesn't Load

### ISSUE THREAD

**Issue by entozoon** [sandord/DpiGonzales#18]
I have Windows 10, .NET version 4.7.02046, two displays (1920x1200 and 3840x2160).

When I run DpiGonzales.exe, it appears in the task manager for maybe 1 second then vanishes.
If I run it from commandline the same thing happens, no errors.

**Comment by sandord** [comment]
I'm sorry to hear that. Could [this](https://github.com/sandord/DpiGonzales/issues/15) be of any help?

**Comment by entozoon** [comment]
Ah, thanks for the link. I figured it out!
Originally, I copied the portable files to `c:\program files\`, which doesn't work. Presumably some windows administrator permissions thing (as I noticed it wasn't creating a .log file)
Putting the files elsewhere runs perfectly!  Brilliant app, thank you

**Comment by sandord** [comment]
Good to hear it works now.

By the way, Windows might have blocked your files due to the fact that they were downloaded from the internet. You can verify this by checking one of the file's properties (probably best to check the exe). If you see an _unblock_ button, you'll know the file has been blocked.

**Comment by entozoon** [comment]
Yeah, windows defender kicks up a fuss but you can get around that easily enough :)
