### ISSUE TITLE
It seems that MS finally fixed mouse speed multiple displays with varying DPIs in W10 Insider Preview build 16273

### ISSUE THREAD

**Issue by sandord** [sandord/DpiGonzales#20]
I noticed that after updating Windows 10 to Insider Preview build 16273, my pointer was way faster than before. After closing down DpiGonzales, I noticed that pointer speed was consistent across all my monitors.

This probably means that DpiGonzales can retire or at least become superfluous for most of us as soon as the final version of Windows 10 Fall Creators Update is released.

If you are on Windows 10 Insider Preview build 16273 or newer, please let us know if you can confirm this or not.

**Comment by entozoon** [comment]
Can confirm, same experience for me on Win 10.0.16299 Build 16299.

Thanks @sandord for this brilliant plugin for all these months!

**Comment by ackvf** [comment]
Windows Version	10.0.17134 Build 17134

I have just found this solution on [SO](https://superuser.com/questions/1051269/mouse-cursor-on-multiple-screens-with-different-ppi/1052431#1052431) so I guess, it's **not adjusted** automatically for me, however it might be because I am using an android tablet as second screen via app called spacedesk, so it might not be recognised properly. Also I have different scaling set on both monitors:

1: DELL XPS 13", 3840x2160 px, scaling 150%
2: Lenovo Yoga Tablet 3 10", 2560x1600 px, scaling 125%

Oh, btw, I am using a precision touchpad.

# edit
Turns out, the Precision touchpad is the reason I am out of luck.
